language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "12"
  - "node"

cache: npm

repo_token: yaETwUmumfZQU9ZJjJhqsfCrtLg9mQVdf

before_script:
  - npm install -g gulp-cli
script:
  - gulp lint
  - npm run coverage:report

notifications:
  email: false
